T: 3
act: relu
amsgrad: false
batchid: 6
batchimage: 8
batchtest: 32
beta1: 0.9
beta2: 0.999
bnneck: false
config: ''
cosine_annealing: false
cpu: false
cuhk03_labeled: false
cutout: false
dampening: 0
data_test: market1501
data_train: market1501
#datadir: ../dataset/dog_191/new_all/dd191_all_o/   # 191 未删
datadir: ../dataset/dog_191/new/d191_o/  # 191 删过

#datadir: ../dataset/pytorch_2_73/   # 73 整理过
decay_type: step_50_80_110
drop_block: false
epochs: 100
epsilon: 1.0e-08
feat_inference: after
feats: 512
gamma: 0.1
h_ratio: 0.3
height: 224
if_labelsmooth: true
loss: 0.5*CrossEntropy+0.5*MSLoss+0.5*MSLoss_o+0.5*CrossEntropy_o
#  0.5*CrossEntropy+0.5*MSLoss
# 0.5*CrossEntropy+0.5*MSLoss+0.5*MSLoss_o+0.5*CrossEntropy_o
lr: 0.0006
lr_decay: 60
margin: 0.7
model: P_r
momentum: 0.9
nGPU: 1
nThread: 4
nep_id: ''
nesterov: false
num_anchors: 1
num_classes: 751
optimizer: ADAM
parts: 6
pcb_different_lr: true
pool: avg
probability: 0.5
random_erasing: true
reset: false
sampler: true
test_every: 1
w_cosine_annealing: true
w_ratio: 1.0
warmup: constant
weight_decay: 0.0005
width: 224
